apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: cnpg-system
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "20m"
        memory: "64Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "10m"
        memory: "16Mi"