apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: vector
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: vector-helm-values