apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vector

resources:
  - 00-oci-repo.yaml
  - 01-helm.yaml

configMapGenerator:
  - name: vector-helm-values
    files:
      - values.yaml=helm-values.yaml
    options:
      disableNameSuffixHash: true