apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gts-stg
spec:
  acme:
    server: https://dv.acme-v02.test-api.pki.goog/directory
    email: ${acme_email}
    privateKeySecretRef:
      name: gts-acme-account
    externalAccountBinding:
      keyID: ${gts_key_id}
      keySecretRef:
        name: cert-manager
        key: gts_eab_secret
    #preferredChain: "R3"
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare
            key: api_token