apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager
  - authentik
  - cert-manager
  - cloudflare-ddns
  - cloudnative-pg
  - envoy-gateway
  - grafana
  - metallb
  - network-policy
  - networking
  - reloader
  - step-ca
  - step-issuer
  - vector
  - vmalert