apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/darak/production
  - ../../../apps/darak/staging
  - ../../../apps/onhouse/production
  - ../../../apps/onhouse/staging