apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: step-issuer-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/step-issuer/issuer
  prune: true
  dependsOn:
    - name: step-issuer-operator
    - name: step-ca-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
