apiVersion: v1
kind: Service
metadata:
  name: authentik-radius
spec:
  selector:
    app.kubernetes.io/name: authentik-radius
  ports:
    - name: radius
      port: 1812
      protocol: UDP
      targetPort: radius
