apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: step-ca-networking
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/step-ca/networking
  prune: true
  dependsOn:
    - name: networking-resources
    - name: step-ca-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
