apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vmalert
spec:
  interval: 10m
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-alert
  ref:
    semver: ">=0.0.0"