apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmalert
  namespace: vmalert
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: vmalert
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: vmalert-helm-values