apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vmalert

resources:
  - 00-oci-repo.yaml
  - 01-helm.yaml

configMapGenerator:
  - name: vmalert-helm-values
    files:
      - values.yaml=helm-values.yaml

configurations:
  - kustomizeconfig.yaml