apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
spec:
  interval: 10m
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  ref:
    semver: ">=0.0.0"