apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: alertmanager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: alertmanager-helm-values