apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-ca-wifi

resources:
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: step-ca-wifi-certs
    files:
      - root_ca.crt
      - intermediate_ca.crt
  - name: step-ca-wifi-ca-json
    files:
      - ca.json
