apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ichika-cd-secrets
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: ichika-cd-secrets
  path: ./
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age