apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - 00-helm-repo.yaml
  - 01-helm.yaml

configMapGenerator:
  - name: grafana-helm-values
    files:
      - values.yaml=helm-values.yaml

configurations:
  - kustomizeconfig.yaml