client ap1-v4 {
    ipaddr = 10.5.0.10
    secret = $ENV{OPENWRT_RADIUS_SECRET}
    require_message_authenticator = yes
}

client ap1-v6 {
    ipv6addr = fdab:d9c3:fb50:5::10
    secret = $ENV{OPENWRT_RADIUS_SECRET}
    require_message_authenticator = yes
}

client ap2-v4 {
    ipaddr = 10.5.0.20
    secret = $ENV{OPENWRT_RADIUS_SECRET}
    require_message_authenticator = yes
}

client ap2-v6 {
    ipv6addr = fdab:d9c3:fb50:5::20
    secret = $ENV{OPENWRT_RADIUS_SECRET}
    require_message_authenticator = yes
}
