proxy server {
    default_fallback = no
}

home_server authentik {
    type = auth
    ipaddr = authentik-radius
    port = 1812
    secret = $ENV{AUTHENTIK_RADIUS_SECRET}
    response_window = 20
}

home_server_pool authentik_pool {
    type = fail-over
    home_server = authentik
}

realm authentik {
    auth_pool = authentik_pool
    nostrip
}
