apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmalert-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/vmalert/operator
  prune: true
  wait: true
  dependsOn:
    - name: alertmanager-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system