apiVersion: v1
kind: Namespace
metadata:
  name: onhouse-prod
  labels:
    darak.dev/domain: onhouse
    darak.dev/env: prod
    darak.dev/app:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted