apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: global-envoy-config
  namespace: networking
spec:
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet: {}
      envoyPDB:
        minAvailable: 2
        # maxUnavailable: 1
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Local
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                metallb.io/loadBalancerIPs: '10.45.10.100,fdab:d9c3:fb50:45:10::100'