apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ../../../../../infra/metallb/base

patches:
  - path: 00-patch-helm.yaml

configMapGenerator:
  - name: metallb-helm-values
    files:
      - values.yaml=helm-values.yaml
    options:
      disableNameSuffixHash: true