apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: darak-prod
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "500m"
        memory: "1Gi"
      min:
        cpu: "25m"
        memory: "32Mi"
