apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: homeassistant
  namespace: darak-prod
spec:
  endpoints:
    - fqdn:
        hostname: homeassistant.rocky-docker-01.internal.darak.dev
        port: 443
  # Force HTTP/1.1 on upstream
  appProtocols:
    - gateway.envoyproxy.io/wss
  tls:
    sni: homeassistant.rocky-docker-01.internal.darak.dev
    # Server certificate is a generic GTS one, so it is not verified here.
    insecureSkipVerify: true
    clientCertificateRef:
      kind: Secret
      name: darak-prod-mtls-backend-client-tls
