apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: authentik
spec:
  secretName: authentik-cert-tls
  issuerRef:
    name: gts-prod
    kind: ClusterIssuer
  commonName: 'auth.darak.dev'
  dnsNames:
    - 'auth.darak.dev'
  privateKey:
    algorithm: ECDSA
    size: 384