apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - ../../../../../infra/traefik/base
  - pdb.yaml

patches:
  - path: patch-helm.yaml

configMapGenerator:
  - name: traefik-helm-values
    files:
      - values.yaml=helm-values.yaml
    options:
      disableNameSuffixHash: true