apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - ../../../../../infra/envoy-gateway/base

patches:
  - path: patch-helm.yaml

configMapGenerator:
  - name: envoy-gateway-helm-values
    files:
      - values.yaml=helm-values.yaml
    options:
      disableNameSuffixHash: true