apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: step-ca
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "25m"
        memory: "64Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "10m"
        memory: "32Mi"
