apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: cloudflare-ddns
spec:
  limits:
    - type: Container
      default:
        cpu: "50m"
        memory: "32Mi"
      defaultRequest:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "100m"
        memory: "64Mi"
      min:
        cpu: "5m"
        memory: "8Mi"
