apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: darak-cd-secrets
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kimiroo/darak-cd-secrets.git
  ref:
    branch: master
  secretRef:
    name: flux-system # reuse same token from flux bootstrap