apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: darak-prod-networking
  namespace: flux-system
spec:
  interval: 10m
  path: ./domain/darak/production/networking
  prune: true
  dependsOn:
    - name: envoy-gateway-networking
    - name: cert-manager-issuer
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system